// FrontendSvelte/src/Header.svelte
<header>
    <h1>DAGBOKEN - Få det ur dig!</h1>
</header>

<style>
    h1 {
    font-family: 'Quicksand', sans-serif; /* Använd samma font som i resten av sidan */
    font-size: 2.5rem; /* Större fontstorlek för att göra den framträdande */
    font-weight: 600; /* Fet stil för att få rubriken att sticka ut */
    color: #d14c84; /* Färg som matchar inläggen */
    text-align: center; /* Centrera rubriken */
    margin-top: -0.5rem; /* Ge lite utrymme ovanför */
    margin-bottom: 2rem; /* Ge lite utrymme under */
    background-color: #fff8fc; /* Bakgrundsfärg för att matcha designen */
    padding: 1rem 0; /* Padding på toppen och botten för att ge rubriken lite luft */
    border-radius: 16px; /* Runda hörn för att matcha de andra elementens stil */
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1); /* Lätt skugga för att ge djup */
  }
</style>

// FrontendVue/src/components/headerComponent.vue
<template>
    <div>
        <h1>DAGBOKEN - Få det ur dig!</h1>
    </div>
</template>

<script>
</script>

<style>
h1 {
    font-family: 'Quicksand', sans-serif; /* Använd samma font som i resten av sidan */
    font-size: 2.5rem; /* Större fontstorlek för att göra den framträdande */
    font-weight: 600; /* Fet stil för att få rubriken att sticka ut */
    color: #d14c84; /* Färg som matchar inläggen */
    text-align: center; /* Centrera rubriken */
    margin-top: -0.5rem; /* Ge lite utrymme ovanför */
    margin-bottom: 2rem; /* Ge lite utrymme under */
    background-color: #fff8fc; /* Bakgrundsfärg för att matcha designen */
    padding: 1rem 0; /* Padding på toppen och botten för att ge rubriken lite luft */
    border-radius: 16px; /* Runda hörn för att matcha de andra elementens stil */
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1); /* Lätt skugga för att ge djup */
  }
  
</style>
